var level = argument0;

var tilesToTurn = -1;
var bombs = -1;
var invisibleBombs = -1;
var horizontalTiles = 4;
var verticalTiles = 4;
var goldCoin = 5;
var gameMode = Game.gameModeWithinTaps;
var tileColors = 2;

Game.levelCompleted = false;
Game.notEnoughTaps = false;
Game.notEnoughTime = false;
Game.loadLevel = true;
Game.bombExploded = false;

with (obj_tile)
{
    colorIndex = 0;
}
with (obj_buttonUndo)
{
    image_alpha = 0.5;
}

if (!instance_exists(obj_tapsLeft))
{
    instance_create(view_xview+view_wview*0.15,120,obj_tapsLeft);
}
if (!instance_exists(obj_levelStartBar))
{
    instance_create(view_xview+view_wview/2,view_yview+view_hview/2,obj_levelStartBar);
}
ResetTurnWaitTime(true);

if (Game.USENEWLEVELCREATION)
{
    switch (level)
    {
        case 0: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 0.1;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 1.2;
                goldCoin = 1;
                break;
        case 1: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 0.2;
                goldCoin = 3;
                break;
        case 2: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 0.1;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 1.2;
                goldCoin = 4;
                break;
        case 3: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 1.1;
                goldCoin = 5;
                break;
        case 4: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 2.2;
                goldCoin = 9;
                break;
        case 5: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.1;
                tilesToTurn[1] = 2.1;
                goldCoin = 6;
                break;
        case 6: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.1;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 2.1;
                goldCoin = 7;
                break;
        case 7: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 0.1;
                tilesToTurn[2] = 0.2;
                tilesToTurn[3] = 1.2;
                tilesToTurn[4] = 2.2;
                goldCoin = 7;
                break;
        case 8: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 2.1;
                goldCoin = 5;
                break;
        case 9: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 2.2;
                goldCoin = 5;
                break;
        case 10:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 0.1;
                tilesToTurn[2] = 0.2;
                goldCoin = 6;
                break;
        case 11:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 0.2;
                tilesToTurn[2] = 1.2;
                goldCoin = 4;
                break;
        case 12:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.1;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 0.2;
                tilesToTurn[3] = 1.2;
                goldCoin = 6;
                break;
        case 13:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 1.2;
                goldCoin = 6;
                break;
        case 14:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 0.2;
                tilesToTurn[6] = 1.2;
                goldCoin = 3;
                break;
        case 15:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 0.2;
                goldCoin = 5;
                break;
        case 16:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 1.2;
                tilesToTurn[6] = 2.2;
                goldCoin = 5;
                break;
        case 17:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 0.2;
                tilesToTurn[2] = 2.2;
                goldCoin = 8;
                break;
        case 18:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 1.2;
                tilesToTurn[5] = 2.2;
                goldCoin = 4;
                break;
        case 19:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 2.2;
                goldCoin = 4;
                break;
        case 20:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 0.1;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 1.2;
                goldCoin = 7;
                break;
        case 21:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 1.1;
                tilesToTurn[5] = 1.2;
                tilesToTurn[6] = 2.2;
                goldCoin = 6;
                break;
        case 22:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 1.2;
                tilesToTurn[6] = 2.2;
                goldCoin = 6;
                break;
        case 23:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 2.2;
                goldCoin = 5;
                break;
        case 24:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 1.2;
                goldCoin = 6;
                break;
        case 25:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 1.2;
                goldCoin = 6;
                break;
        case 26:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.1;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 1.2;
                tilesToTurn[4] = 2.2;
                goldCoin = 4;
                break;
        case 27:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 0.1;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 1.2;
                goldCoin = 5;
                break;
        case 28:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 0.2;
                goldCoin = 6;
                break;
        case 29:horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 1.2;
                goldCoin = 3;
                break;
        case 30:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 3.2;
                tilesToTurn[4] = 2.3;
                tilesToTurn[5] = 3.3;
                goldCoin = 2;
                break;
        case 31:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 3.1;
                tilesToTurn[4] = 1.2;
                tilesToTurn[5] = 2.2;
                goldCoin = 2;
                break;
        case 32:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 1.1;
                tilesToTurn[5] = 2.1;
                tilesToTurn[6] = 0.2;
                tilesToTurn[7] = 1.2;
                tilesToTurn[8] = 3.2;
                tilesToTurn[9] = 0.3;
                tilesToTurn[10] = 2.3;
                goldCoin = 5;
                break;
        case 33:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.1;
                tilesToTurn[1] = 2.1;
                tilesToTurn[2] = 1.2;
                tilesToTurn[3] = 2.2;
                goldCoin = 6;
                break;
        case 34:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.3;
                tilesToTurn[3] = 3.3;
                goldCoin = 6;
                break;
        case 35:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 1.2;
                tilesToTurn[5] = 2.2;
                tilesToTurn[6] = 0.3;
                tilesToTurn[7] = 3.3;
                goldCoin = 4;
                break;
        case 36:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 1.3;
                tilesToTurn[3] = 2.3;
                goldCoin = 6;
                break;
        case 37:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 0.1;
                tilesToTurn[2] = 2.2;
                tilesToTurn[3] = 3.2;
                tilesToTurn[4] = 2.3;
                tilesToTurn[5] = 3.3;
                goldCoin = 6;
                break;
        case 38:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 2.1;
                tilesToTurn[2] = 0.2;
                tilesToTurn[3] = 1.2;
                tilesToTurn[4] = 3.2;
                tilesToTurn[5] = 2.3;
                goldCoin = 4;
                break;
        case 39:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 3.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 3.2;
                tilesToTurn[6] = 0.3;
                tilesToTurn[7] = 3.3;
                goldCoin = 6;
                break;
        case 40:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.1;
                tilesToTurn[1] = 2.1;
                tilesToTurn[2] = 1.2;
                tilesToTurn[3] = 2.2;
                bombs[0] = 3.3;
                goldCoin = 6;
                break;
        case 41:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 0.3;
                bombs[0] = 0.0;
                goldCoin = 5;
                break;
        case 42:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 2.2;
                tilesToTurn[6] = 1.3;
                tilesToTurn[7] = 3.3;
                bombs[0] = 2.3;
                goldCoin = 7;
                break;
        case 43:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 3.0;
                tilesToTurn[4] = 3.1;
                tilesToTurn[5] = 0.2;
                tilesToTurn[6] = 3.2;
                tilesToTurn[7] = 1.3;
                tilesToTurn[8] = 3.3;
                goldCoin = 5;
                break;
        case 44:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 3.1;
                tilesToTurn[6] = 0.2;
                tilesToTurn[7] = 1.2;
                tilesToTurn[8] = 3.2;
                tilesToTurn[9] = 1.3;
                tilesToTurn[10] = 2.3;
                tilesToTurn[11] = 3.3;
                goldCoin = 4;
                break;
        case 45:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 3.1;
                tilesToTurn[6] = 2.2;
                tilesToTurn[7] = 3.2;
                tilesToTurn[8] = 0.3;
                tilesToTurn[9] = 3.3;
                bombs[0] = 3.0;
                goldCoin = 6;
                break;
        case 46:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 3.1;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 2.2;
                tilesToTurn[5] = 1.3;
                bombs[0] = 0.0;
                bombs[1] = 3.3;
                goldCoin = 6;
                break;
        case 47:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.2;
                tilesToTurn[2] = 2.2;
                tilesToTurn[3] = 3.2;
                tilesToTurn[4] = 0.3;
                tilesToTurn[5] = 1.3;
                tilesToTurn[6] = 3.3;
                bombs[0] = 2.3;
                goldCoin = 6;
                break;
        case 48:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 2.2;
                tilesToTurn[5] = 3.2;
                tilesToTurn[6] = 0.3;
                tilesToTurn[7] = 2.3;
                bombs[0] = 1.1;
                goldCoin = 4;
                break;
        case 49:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.1;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 1.3;
                tilesToTurn[5] = 3.3;
                bombs[0] = 1.1;
                bombs[1] = 2.2;
                goldCoin = 6;
                break;
        case 50:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 3.1;
                tilesToTurn[5] = 1.2;
                tilesToTurn[6] = 3.2;
                tilesToTurn[7] = 0.3;
                tilesToTurn[8] = 1.3;
                tilesToTurn[9] = 3.3;
                goldCoin = 4;
                break;
        case 51:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 2.2;
                tilesToTurn[6] = 3.2;
                tilesToTurn[7] = 0.3;
                tilesToTurn[8] = 2.3;
                goldCoin = 3;
                break;
        case 52:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 0.3;
                tilesToTurn[6] = 3.3;
                goldCoin = 6;
                break;
        case 53:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 1.2;
                tilesToTurn[5] = 2.2;
                tilesToTurn[6] = 3.2;
                tilesToTurn[7] = 0.3;
                tilesToTurn[8] = 2.3;
                tilesToTurn[9] = 3.3;
                goldCoin = 6;
                break;
        case 54:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 3.1;
                tilesToTurn[4] = 1.2;
                tilesToTurn[5] = 3.2;
                tilesToTurn[6] = 0.3;
                tilesToTurn[7] = 3.3;
                invisibleBombs[0] = 0.1;
                invisibleBombs[1] = 2.3;
                goldCoin = 4;
                break;
        case 55:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 0.3;
                tilesToTurn[6] = 3.3;
                invisibleBombs[0] = 3.0;
                goldCoin = 7;
                break;
        case 56:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 3.0;
                tilesToTurn[1] = 0.2;
                tilesToTurn[2] = 1.2;
                tilesToTurn[3] = 0.3;
                tilesToTurn[4] = 1.3;
                invisibleBombs[0] = 0.0;
                goldCoin = 7;
                break;
        case 57:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 0.1;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 2.2;
                tilesToTurn[5] = 2.3;
                tilesToTurn[6] = 3.3;
                goldCoin = 5;
                break;
        case 58:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 3.0;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 3.1;
                tilesToTurn[6] = 1.2;
                tilesToTurn[7] = 3.2;
                tilesToTurn[8] = 0.3;
                tilesToTurn[9] = 1.3;
                tilesToTurn[10] = 2.3;
                tilesToTurn[11] = 3.3;
                goldCoin = 5;
                break;
        case 59:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 3.1;
                tilesToTurn[5] = 0.2;
                tilesToTurn[6] = 2.2;
                tilesToTurn[7] = 0.3;
                tilesToTurn[8] = 1.3;
                tilesToTurn[9] = 3.3;
                goldCoin = 6;
                break;
        case 60:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 0.2;
                tilesToTurn[6] = 1.2;
                tilesToTurn[7] = 0.3;
                invisibleBombs[0] = 0.0;
                goldCoin = 2;
                break;
        case 61:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 1.1;
                tilesToTurn[5] = 3.1;
                tilesToTurn[6] = 2.2;
                tilesToTurn[7] = 0.3;
                tilesToTurn[8] = 2.3;
                tilesToTurn[9] = 3.3;
                goldCoin = 4;
                break;
        case 62:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 3.0;
                tilesToTurn[4] = 0.1;
                tilesToTurn[5] = 1.1;
                tilesToTurn[6] = 2.1;
                tilesToTurn[7] = 3.1;
                tilesToTurn[8] = 0.2;
                tilesToTurn[9] = 1.2;
                tilesToTurn[10] = 2.2;
                tilesToTurn[11] = 3.2;
                tilesToTurn[12] = 0.3;
                tilesToTurn[13] = 1.3;
                tilesToTurn[14] = 2.3;
                tilesToTurn[15] = 3.3;
                goldCoin = 10;
                break;
        case 63:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 3.1;
                tilesToTurn[6] = 0.2;
                tilesToTurn[7] = 1.2;
                tilesToTurn[8] = 2.2;
                tilesToTurn[9] = 3.2;
                tilesToTurn[10] = 1.3;
                tilesToTurn[11] = 2.3;
                invisibleBombs[0] = 0.0;
                invisibleBombs[1] = 3.0;
                invisibleBombs[2] = 0.3;
                invisibleBombs[3] = 3.3;
                goldCoin = 4;
                break;
        case 64:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 3.1;
                tilesToTurn[6] = 1.2;
                tilesToTurn[7] = 2.2;
                tilesToTurn[8] = 3.2;
                tilesToTurn[9] = 0.3;
                tilesToTurn[10] = 1.3;
                tilesToTurn[11] = 2.3;
                tilesToTurn[12] = 3.3;
                goldCoin = 5;
                break;
        case 65:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 0.2;
                tilesToTurn[4] = 3.2;
                tilesToTurn[5] = 1.3;
                tilesToTurn[6] = 2.3;
                goldCoin = 5;
                break;
        case 66:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 3.1;
                tilesToTurn[6] = 0.3;
                tilesToTurn[7] = 1.3;
                tilesToTurn[8] = 2.3;
                tilesToTurn[9] = 3.3;
                bombs[0] = 1.0;
                bombs[1] = 2.0;
                goldCoin = 4;
                break;
        case 67:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 3.0;
                tilesToTurn[4] = 3.1;
                tilesToTurn[5] = 0.2;
                tilesToTurn[6] = 3.2;
                tilesToTurn[7] = 1.3;
                tilesToTurn[8] = 3.3;
                bombs[0] = 1.1;
                bombs[1] = 2.2;
                goldCoin = 5;
                break;
        case 68:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 1.2;
                tilesToTurn[6] = 2.2;
                tilesToTurn[7] = 3.2;
                tilesToTurn[8] = 1.3;
                tilesToTurn[9] = 3.3;
                invisibleBombs[0] = 1.0;
                invisibleBombs[1] = 3.0;
                invisibleBombs[2] = 0.3;
                invisibleBombs[3] = 2.3;
                goldCoin = 4;
                break;
        case 69:horizontalTiles = 4;
                verticalTiles = 4;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 3.1;
                tilesToTurn[4] = 1.3;
                tilesToTurn[5] = 2.3;
                invisibleBombs[0] = 1.0;
                invisibleBombs[1] = 2.0;
                invisibleBombs[2] = 0.3;
                invisibleBombs[3] = 3.3;
                goldCoin = 4;
                break;
        case 70:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 2.1;
                tilesToTurn[2] = 0.2;
                tilesToTurn[3] = 1.2;
                tilesToTurn[4] = 3.2;
                tilesToTurn[5] = 4.2;
                tilesToTurn[6] = 1.4;
                tilesToTurn[7] = 3.4;
                goldCoin = 5;
                break;
        case 71:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 0.1;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 2.2;
                tilesToTurn[4] = 3.3;
                tilesToTurn[5] = 4.3;
                tilesToTurn[6] = 3.4;
                goldCoin = 3;
                break;
        case 72:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 3.1;
                tilesToTurn[5] = 4.1;
                tilesToTurn[6] = 0.3;
                tilesToTurn[7] = 1.3;
                tilesToTurn[8] = 3.3;
                tilesToTurn[9] = 4.3;
                tilesToTurn[10] = 1.4;
                tilesToTurn[11] = 3.4;
                goldCoin = 4;
                break;
        case 73:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 4.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 0.2;
                tilesToTurn[6] = 1.2;
                tilesToTurn[7] = 3.2;
                tilesToTurn[8] = 4.2;
                tilesToTurn[9] = 2.3;
                tilesToTurn[10] = 4.3;
                tilesToTurn[11] = 0.4;
                tilesToTurn[12] = 2.4;
                tilesToTurn[13] = 3.4;
                goldCoin = 6;
                break;
        case 74:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 0.2;
                tilesToTurn[2] = 2.2;
                tilesToTurn[3] = 4.2;
                tilesToTurn[4] = 2.4;
                goldCoin = 5;
                break;
        case 75:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 4.1;
                tilesToTurn[5] = 1.2;
                tilesToTurn[6] = 2.2;
                tilesToTurn[7] = 3.2;
                tilesToTurn[8] = 0.3;
                tilesToTurn[9] = 2.3;
                tilesToTurn[10] = 4.3;
                tilesToTurn[11] = 1.4;
                tilesToTurn[12] = 3.4;
                goldCoin = 9;
                break;
        case 76:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 4.1;
                tilesToTurn[5] = 2.2;
                tilesToTurn[6] = 0.3;
                tilesToTurn[7] = 2.3;
                tilesToTurn[8] = 1.4;
                tilesToTurn[9] = 3.4;
                tilesToTurn[10] = 4.4;
                goldCoin = 7;
                break;
        case 77:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 3.1;
                tilesToTurn[2] = 0.2;
                tilesToTurn[3] = 2.2;
                tilesToTurn[4] = 4.2;
                tilesToTurn[5] = 1.3;
                tilesToTurn[6] = 2.4;
                goldCoin = 7;
                break;
        case 78:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 4.1;
                tilesToTurn[4] = 0.3;
                tilesToTurn[5] = 4.3;
                tilesToTurn[6] = 1.4;
                tilesToTurn[7] = 3.4;
                bombs[0] = 0.0;
                bombs[1] = 4.0;
                bombs[2] = 0.4;
                bombs[3] = 4.4;
                goldCoin = 8;
                break;
        case 79:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 4.1;
                tilesToTurn[6] = 0.2;
                tilesToTurn[7] = 1.2;
                tilesToTurn[8] = 3.2;
                tilesToTurn[9] = 4.2;
                tilesToTurn[10] = 0.3;
                tilesToTurn[11] = 2.3;
                tilesToTurn[12] = 4.3;
                tilesToTurn[13] = 1.4;
                tilesToTurn[14] = 2.4;
                tilesToTurn[15] = 3.4;
                goldCoin = 4;
                break;
        case 80:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 2.0;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 3.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 1.2;
                tilesToTurn[6] = 3.2;
                tilesToTurn[7] = 4.2;
                tilesToTurn[8] = 1.3;
                tilesToTurn[9] = 2.3;
                tilesToTurn[10] = 3.3;
                tilesToTurn[11] = 2.4;
                goldCoin = 8;
                break;
        case 81:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 3.0;
                tilesToTurn[1] = 4.0;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 2.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 1.2;
                tilesToTurn[6] = 2.2;
                tilesToTurn[7] = 1.3;
                tilesToTurn[8] = 2.3;
                tilesToTurn[9] = 3.4;
                tilesToTurn[10] = 4.4;
                goldCoin = 5;
                break;
        case 82:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 3.1;
                tilesToTurn[6] = 0.2;
                tilesToTurn[7] = 1.2;
                tilesToTurn[8] = 3.2;
                tilesToTurn[9] = 4.2;
                tilesToTurn[10] = 0.3;
                tilesToTurn[11] = 1.3;
                tilesToTurn[12] = 2.3;
                tilesToTurn[13] = 3.3;
                tilesToTurn[14] = 4.3;
                tilesToTurn[15] = 0.4;
                tilesToTurn[16] = 2.4;
                tilesToTurn[17] = 4.4;
                goldCoin = 6;
                break;
        case 83:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 1.1;
                tilesToTurn[4] = 2.1;
                tilesToTurn[5] = 3.1;
                tilesToTurn[6] = 4.1;
                tilesToTurn[7] = 0.2;
                tilesToTurn[8] = 2.2;
                tilesToTurn[9] = 4.2;
                tilesToTurn[10] = 0.3;
                tilesToTurn[11] = 1.3;
                tilesToTurn[12] = 2.3;
                tilesToTurn[13] = 3.3;
                tilesToTurn[14] = 4.3;
                tilesToTurn[15] = 1.4;
                tilesToTurn[16] = 3.4;
                goldCoin = 7;
                break;
        case 84:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 0.0;
                tilesToTurn[1] = 1.0;
                tilesToTurn[2] = 2.0;
                tilesToTurn[3] = 3.0;
                tilesToTurn[4] = 4.0;
                tilesToTurn[5] = 0.1;
                tilesToTurn[6] = 1.1;
                tilesToTurn[7] = 3.1;
                tilesToTurn[8] = 4.1;
                tilesToTurn[9] = 1.2;
                tilesToTurn[10] = 2.2;
                tilesToTurn[11] = 3.2;
                tilesToTurn[12] = 0.3;
                tilesToTurn[13] = 1.3;
                tilesToTurn[14] = 3.3;
                tilesToTurn[15] = 4.3;
                tilesToTurn[16] = 0.4;
                tilesToTurn[17] = 1.4;
                tilesToTurn[18] = 2.4;
                tilesToTurn[19] = 3.4;
                tilesToTurn[20] = 4.4;
                goldCoin = 7;
                break;
        case 85:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 0.2;
                tilesToTurn[1] = 2.2;
                tilesToTurn[2] = 4.2;
                tilesToTurn[3] = 2.3;
                tilesToTurn[4] = 1.4;
                tilesToTurn[5] = 2.4;
                tilesToTurn[6] = 3.4;
                goldCoin = 5;
                break;
        case 86:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 3.0;
                tilesToTurn[3] = 0.1;
                tilesToTurn[4] = 4.1;
                tilesToTurn[5] = 0.2;
                tilesToTurn[6] = 2.2;
                tilesToTurn[7] = 4.2;
                tilesToTurn[8] = 0.3;
                tilesToTurn[9] = 1.4;
                tilesToTurn[10] = 2.4;
                tilesToTurn[11] = 4.4;
                invisibleBombs[0] = 1.1;
                invisibleBombs[1] = 3.3;
                goldCoin = 6;
                break;
        case 87:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 2.0;
                tilesToTurn[2] = 0.1;
                tilesToTurn[3] = 3.1;
                tilesToTurn[4] = 1.2;
                tilesToTurn[5] = 3.2;
                tilesToTurn[6] = 1.3;
                tilesToTurn[7] = 4.3;
                tilesToTurn[8] = 2.4;
                tilesToTurn[9] = 3.4;
                invisibleBombs[0] = 0.0;
                invisibleBombs[1] = 4.0;
                invisibleBombs[2] = 4.1;
                invisibleBombs[3] = 0.3;
                invisibleBombs[4] = 0.4;
                invisibleBombs[5] = 4.4;
                goldCoin = 7;
                break;
        case 88:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 0.1;
                tilesToTurn[1] = 1.1;
                tilesToTurn[2] = 2.1;
                tilesToTurn[3] = 3.1;
                tilesToTurn[4] = 4.1;
                tilesToTurn[5] = 0.2;
                tilesToTurn[6] = 2.2;
                tilesToTurn[7] = 4.2;
                tilesToTurn[8] = 0.3;
                tilesToTurn[9] = 1.3;
                tilesToTurn[10] = 3.3;
                tilesToTurn[11] = 4.3;
                tilesToTurn[12] = 1.4;
                tilesToTurn[13] = 2.4;
                tilesToTurn[14] = 3.4;
                goldCoin = 10;
                break;
        case 89:horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 1.0;
                tilesToTurn[1] = 3.0;
                tilesToTurn[2] = 1.1;
                tilesToTurn[3] = 3.1;
                tilesToTurn[4] = 0.2;
                tilesToTurn[5] = 4.2;
                tilesToTurn[6] = 0.3;
                tilesToTurn[7] = 4.3;
                tilesToTurn[8] = 0.4;
                tilesToTurn[9] = 1.4;
                tilesToTurn[10] = 3.4;
                tilesToTurn[11] = 4.4;
                bombs[0] = 0.0;
                bombs[1] = 4.0;
                bombs[2] = 1.2;
                bombs[3] = 3.2;
                goldCoin = 6;
                break;
    }
    for (var i=0;i<array_length_1d(tilesToTurn);i++)
    {
        if (floor(tilesToTurn[i]) > horizontalTiles || round(tilesToTurn[i]%1*10) > verticalTiles)
        {
            //show_debug_message("Can't use new level creation, it'll cause an error. Using old level creation.");
            Game.USENEWLEVELCREATION = false;
            LoadLevel(argument0);
            break;
        }
    }
}

/*
[OLD LEVEL CREATION CODE]
*/
if (!Game.USENEWLEVELCREATION)
{
    switch (level)
    {
        case 0: horizontalTiles = 3;
                verticalTiles = 3;
                tilesToTurn[0] = 4;
                break;
        case 1: horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 0;
                tilesToTurn[1] = 6;
                tilesToTurn[2] = 12;
                tilesToTurn[3] = 18;
                tilesToTurn[4] = 24;
                bombs[0] = 3;
                break;
        case 2: tilesToTurn[0] = 3;
                tilesToTurn[1] = 6;
                tilesToTurn[2] = 9;
                tilesToTurn[3] = 12;
                bombs[0] = 4;
                bombs[1] = 5;
                break;
        case 3: horizontalTiles = 5;
                verticalTiles = 5;
                tilesToTurn[0] = 0;
                tilesToTurn[1] = 3;
                tilesToTurn[2] = 12;
                tilesToTurn[3] = 15;
                bombs[0] = 4;
                bombs[1] = 5;
                break;
        case 4: tilesToTurn[0] = 5;
                tilesToTurn[1] = 6;
                tilesToTurn[2] = 9;
                tilesToTurn[3] = 10;
                break;
        case 5: tilesToTurn[0] = 4;
                tilesToTurn[1] = 5;
                tilesToTurn[2] = 10;
                tilesToTurn[3] = 11;
                break;
        case 6: tilesToTurn[0] = 0;
                tilesToTurn[1] = 5;
                tilesToTurn[2] = 10;
                tilesToTurn[3] = 3;
                tilesToTurn[4] = 6;
                tilesToTurn[5] = 9;
                break;
        case 7: tilesToTurn[0] = 5;
                tilesToTurn[1] = 10;
                tilesToTurn[2] = 3;
                tilesToTurn[3] = 12;
                break;
        case 8: tilesToTurn[0] = 0;
                tilesToTurn[1] = 9;
                tilesToTurn[2] = 2;
                tilesToTurn[3] = 11;
                tilesToTurn[4] = 14;
                tilesToTurn[5] = 13;
                break;
        case 9: tilesToTurn[0] = 0;
                tilesToTurn[1] = 9;
                tilesToTurn[2] = 2;
                tilesToTurn[3] = 11;
                tilesToTurn[4] = 14;
                tilesToTurn[5] = 13;
                break;
        case 10:tilesToTurn[0] = 0;
                tilesToTurn[1] = 2;
                tilesToTurn[2] = 5;
                tilesToTurn[3] = 7;
                tilesToTurn[4] = 8;
                tilesToTurn[5] = 10;
                tilesToTurn[6] = 13;
                tilesToTurn[7] = 15;
                break;
        case 11:tilesToTurn[0] = 0;
                tilesToTurn[1] = 1;
                tilesToTurn[2] = 2;
                tilesToTurn[3] = 15;
                tilesToTurn[4] = 14;
                tilesToTurn[5] = 13;
                break;
    }
    goldCoin = array_length_1d(tilesToTurn);
}
/*
[OLD LEVEL CREATION CODE]
*/
Game.tilesToTurn = tilesToTurn;
Game.gameMode = gameMode;
Game.bombs = bombs;
Game.invisibleBombs = invisibleBombs;
Game.currentHorizontalTiles = horizontalTiles;
Game.currentVerticalTiles = verticalTiles;
Game.goldCoin = goldCoin;
Game.currentTileColors = tileColors;
/*
for (var i=0;i<array_length_1d(tilesToTurn);i++)
{
    TurnTiles(Game.board[tilesToTurn[i]%Game.currentHorizontalTiles,floor(tilesToTurn[i]/Game.currentVerticalTiles)]);
}

with (obj_tile)
{
    turn = 0;
}
